### ISSUE TITLE
Installation failed in windows 10 python 3.9

### ISSUE THREAD

**Issue by sparkingdark** [zarr-developers/numcodecs#261]
#### Problem description

While I am installing zarr and numecodecs it's failed with the following error, is their any fix available.

```
C:\Users\debo\Downloads\Hub-master\Hub-master>python -m pip install --upgrade numcodecs
Collecting numcodecs
  Using cached numcodecs-0.7.2.tar.gz (3.9 MB)
Requirement already satisfied: numpy>=1.7 in c:\users\debo\appdata\local\programs\python\python39\lib\site-packages (from numcodecs) (1.19.4)
Building wheels for collected packages: numcodecs
  Building wheel for numcodecs (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\debo\AppData\Local\Programs\Python\Python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\debo\\AppData\\Local\\Temp\\pip-install-ygdv_jgu\\numcodecs_ebf383ae4897413487542e3eeeb713e5\\setup.py'"'"'; __file__='"'"'C:\\Users\\debo\\AppData\\Local\\Temp\\pip-install-ygdv_jgu\\numcodecs_ebf383ae4897413487542e3eeeb713e5\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\debo\AppData\Local\Temp\pip-wheel-psdky82n'
       cwd: C:\Users\debo\AppData\Local\Temp\pip-install-ygdv_jgu\numcodecs_ebf383ae4897413487542e3eeeb713e5\
  Complete output (140 lines):
  [numcodecs] setting up Blosc extension
  [numcodecs] compiling Blosc extension with SSE2 support
  [numcodecs] compiling Blosc extension with AVX2 support
  [numcodecs] setting up Zstandard extension
  [numcodecs] setting up LZ4 extension
  [numcodecs] setting up compat extension
  [numcodecs] setting up vlen extension
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\numcodecs
  copying .\numcodecs\abc.py -> build\lib.win-amd64-3.9\numcodecs
  copying .\numcodecs\astype.py -> build\lib.win-amd64-3.9\numcodecs
  copying .\numcodecs\base64.py -> build\lib.win-amd64-3.9\numcodecs
  copying .\numcodecs\bz2.py -> build\lib.win-amd64-3.9\numcodecs
  copying .\numcodecs\categorize.py -> build\lib.win-amd64-3.9\numcodecs
  copying .\numcodecs\checksum32.py -> build\lib.win-amd64-3.9\numcodecs
  copying .\numcodecs\compat.py -> build\lib.win-amd64-3.9\numcodecs
  copying .\numcodecs\delta.py -> build\lib.win-amd64-3.9\numcodecs
  copying .\numcodecs\fixedscaleoffset.py -> build\lib.win-amd64-3.9\numcodecs
  copying .\numcodecs\gzip.py -> build\lib.win-amd64-3.9\numcodecs
  copying .\numcodecs\json.py -> build\lib.win-amd64-3.9\numcodecs
  copying .\numcodecs\lzma.py -> build\lib.win-amd64-3.9\numcodecs
  copying .\numcodecs\msgpacks.py -> build\lib.win-amd64-3.9\numcodecs
  copying .\numcodecs\packbits.py -> build\lib.win-amd64-3.9\numcodecs
  copying .\numcodecs\pickles.py -> build\lib.win-amd64-3.9\numcodecs
  copying .\numcodecs\quantize.py -> build\lib.win-amd64-3.9\numcodecs
  copying .\numcodecs\registry.py -> build\lib.win-amd64-3.9\numcodecs
  copying .\numcodecs\version.py -> build\lib.win-amd64-3.9\numcodecs
  copying .\numcodecs\zlib.py -> build\lib.win-amd64-3.9\numcodecs
  copying .\numcodecs\__init__.py -> build\lib.win-amd64-3.9\numcodecs
  creating build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\common.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_astype.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_base64.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_blosc.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_bz2.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_categorize.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_checksum32.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_compat.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_delta.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_fixedscaleoffset.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_gzip.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_json.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_lz4.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_lzma.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_msgpacks.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_packbits.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_pickles.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_quantize.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_registry.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_vlen_array.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_vlen_bytes.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_vlen_utf8.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_zlib.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\test_zstd.py -> build\lib.win-amd64-3.9\numcodecs\tests
  copying .\numcodecs\tests\__init__.py -> build\lib.win-amd64-3.9\numcodecs\tests
  running build_ext
  building 'numcodecs.blosc' extension
  creating build\temp.win-amd64-3.9
  creating build\temp.win-amd64-3.9\Release
  creating build\temp.win-amd64-3.9\Release\c-blosc
  creating build\temp.win-amd64-3.9\Release\c-blosc\blosc
  creating build\temp.win-amd64-3.9\Release\c-blosc\internal-complibs
  creating build\temp.win-amd64-3.9\Release\c-blosc\internal-complibs\lz4-1.9.2
  creating build\temp.win-amd64-3.9\Release\c-blosc\internal-complibs\snappy-1.1.1
  creating build\temp.win-amd64-3.9\Release\c-blosc\internal-complibs\zlib-1.2.8
  creating build\temp.win-amd64-3.9\Release\c-blosc\internal-complibs\zstd-1.4.4
  creating build\temp.win-amd64-3.9\Release\c-blosc\internal-complibs\zstd-1.4.4\common
  creating build\temp.win-amd64-3.9\Release\c-blosc\internal-complibs\zstd-1.4.4\compress
  creating build\temp.win-amd64-3.9\Release\c-blosc\internal-complibs\zstd-1.4.4\decompress
  creating build\temp.win-amd64-3.9\Release\c-blosc\internal-complibs\zstd-1.4.4\dictBuilder
  creating build\temp.win-amd64-3.9\Release\numcodecs
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG 
/MD -DHAVE_LZ4=1 -DHAVE_SNAPPY=1 -DHAVE_ZLIB=1 -DHAVE_ZSTD=1 -D__SSE2__=1 -D__AVX2__=1 -Ic-blosc\blosc -Ic-blosc/internal-complibs\lz4-1.9.2 -Ic-blosc/internal-complibs\snappy-1.1.1 -Ic-blosc/internal-complibs\zlib-1.2.8 -Ic-blosc/internal-complibs\zstd-1.4.4 -Ic-blosc/internal-complibs\zstd-1.4.4\common -Ic-blosc/internal-complibs\zstd-1.4.4\compress -Ic-blosc/internal-complibs\zstd-1.4.4\decompress -Ic-blosc/internal-complibs\zstd-1.4.4\deprecated -Ic-blosc/internal-complibs\zstd-1.4.4\dictBuilder -Ic-blosc/internal-complibs\zstd-1.4.4\dll -Ic-blosc/internal-complibs\zstd-1.4.4\legacy -IC:\Users\debo\AppData\Local\Programs\Python\Python39\include -IC:\Users\debo\AppData\Local\Programs\Python\Python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include /Tcc-blosc/blosc\bitshuffle-avx2.c /Fobuild\temp.win-amd64-3.9\Release\c-blosc/blosc\bitshuffle-avx2.obj -DSHUFFLE_SSE2_ENABLED -DSHUFFLE_AVX2_ENABLED
  bitshuffle-avx2.c
  C:\Users\debo\AppData\Local\Temp\pip-install-ygdv_jgu\numcodecs_ebf383ae4897413487542e3eeeb713e5\c-blosc\blosc\blosc-common.h(13): fatal error C1083: Cannot open include file: 'string.h': No such file or directory
  [numcodecs] command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  Traceback (most recent call last):
    File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\_msvccompiler.py", line 401, in compile
      self.spawn(args)
    File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\_msvccompiler.py", line 507, in spawn
      return super().spawn(cmd)
    File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\ccompiler.py", line 910, in spawn
      spawn(cmd, dry_run=self.dry_run)
    File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\spawn.py", line 87, in spawn
      raise DistutilsExecError(
  distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "C:\Users\debo\AppData\Local\Temp\pip-install-ygdv_jgu\numcodecs_ebf383ae4897413487542e3eeeb713e5\setup.py", line 276, in build_extension      build_ext.build_extension(self, ext)
    File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\command\build_ext.py", line 529, in build_extension
      objects = self.compiler.compile(sources,
    File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\_msvccompiler.py", line 403, in compile
      raise CompileError(msg)
  distutils.errors.CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\debo\AppData\Local\Temp\pip-install-ygdv_jgu\numcodecs_ebf383ae4897413487542e3eeeb713e5\setup.py", line 350, in <module>       
      run_setup(with_extensions)
    File "C:\Users\debo\AppData\Local\Temp\pip-install-ygdv_jgu\numcodecs_ebf383ae4897413487542e3eeeb713e5\setup.py", line 300, in run_setup      
      setup(
    File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\debo\AppData\Local\Temp\pip-install-ygdv_jgu\numcodecs_ebf383ae4897413487542e3eeeb713e5\setup.py", line 269, in run
      build_ext.run(self)
    File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\debo\AppData\Local\Temp\pip-install-ygdv_jgu\numcodecs_ebf383ae4897413487542e3eeeb713e5\setup.py", line 279, in build_extension      raise BuildFailed()
  __main__.BuildFailed
  ----------------------------------------
  ERROR: Failed building wheel for numcodecs
  Running setup.py clean for numcodecs
Failed to build numcodecs
Installing collected packages: numcodecs
    Running setup.py install for numcodecs ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\debo\AppData\Local\Programs\Python\Python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\debo\\AppData\\Local\\Temp\\pip-install-ygdv_jgu\\numcodecs_ebf383ae4897413487542e3eeeb713e5\\setup.py'"'"'; __file__='"'"'C:\\Users\\debo\\AppData\\Local\\Temp\\pip-install-ygdv_jgu\\numcodecs_ebf383ae4897413487542e3eeeb713e5\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\debo\AppData\Local\Temp\pip-record-80uvqj77\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\debo\AppData\Local\Programs\Python\Python39\Include\numcodecs'
         cwd: C:\Users\debo\AppData\Local\Temp\pip-install-ygdv_jgu\numcodecs_ebf383ae4897413487542e3eeeb713e5\
    Complete output (142 lines):
    [numcodecs] setting up Blosc extension
    [numcodecs] compiling Blosc extension with SSE2 support
    [numcodecs] compiling Blosc extension with AVX2 support
    [numcodecs] setting up Zstandard extension
    [numcodecs] setting up LZ4 extension
    [numcodecs] setting up compat extension
    [numcodecs] setting up vlen extension
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\numcodecs
    copying .\numcodecs\abc.py -> build\lib.win-amd64-3.9\numcodecs
    copying .\numcodecs\astype.py -> build\lib.win-amd64-3.9\numcodecs
    copying .\numcodecs\base64.py -> build\lib.win-amd64-3.9\numcodecs
    copying .\numcodecs\bz2.py -> build\lib.win-amd64-3.9\numcodecs
    copying .\numcodecs\categorize.py -> build\lib.win-amd64-3.9\numcodecs
    copying .\numcodecs\checksum32.py -> build\lib.win-amd64-3.9\numcodecs
    copying .\numcodecs\compat.py -> build\lib.win-amd64-3.9\numcodecs
    copying .\numcodecs\delta.py -> build\lib.win-amd64-3.9\numcodecs
    copying .\numcodecs\fixedscaleoffset.py -> build\lib.win-amd64-3.9\numcodecs
    copying .\numcodecs\gzip.py -> build\lib.win-amd64-3.9\numcodecs
    copying .\numcodecs\json.py -> build\lib.win-amd64-3.9\numcodecs
    copying .\numcodecs\lzma.py -> build\lib.win-amd64-3.9\numcodecs
    copying .\numcodecs\msgpacks.py -> build\lib.win-amd64-3.9\numcodecs
    copying .\numcodecs\packbits.py -> build\lib.win-amd64-3.9\numcodecs
    copying .\numcodecs\pickles.py -> build\lib.win-amd64-3.9\numcodecs
    copying .\numcodecs\quantize.py -> build\lib.win-amd64-3.9\numcodecs
    copying .\numcodecs\registry.py -> build\lib.win-amd64-3.9\numcodecs
    copying .\numcodecs\version.py -> build\lib.win-amd64-3.9\numcodecs
    copying .\numcodecs\zlib.py -> build\lib.win-amd64-3.9\numcodecs
    copying .\numcodecs\__init__.py -> build\lib.win-amd64-3.9\numcodecs
    creating build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\common.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_astype.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_base64.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_blosc.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_bz2.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_categorize.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_checksum32.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_compat.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_delta.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_fixedscaleoffset.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_gzip.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_json.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_lz4.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_lzma.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_msgpacks.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_packbits.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_pickles.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_quantize.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_registry.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_vlen_array.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_vlen_bytes.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_vlen_utf8.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_zlib.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\test_zstd.py -> build\lib.win-amd64-3.9\numcodecs\tests
    copying .\numcodecs\tests\__init__.py -> build\lib.win-amd64-3.9\numcodecs\tests
    running build_ext
    building 'numcodecs.blosc' extension
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\c-blosc
    creating build\temp.win-amd64-3.9\Release\c-blosc\blosc
    creating build\temp.win-amd64-3.9\Release\c-blosc\internal-complibs
    creating build\temp.win-amd64-3.9\Release\c-blosc\internal-complibs\lz4-1.9.2
    creating build\temp.win-amd64-3.9\Release\c-blosc\internal-complibs\snappy-1.1.1
    creating build\temp.win-amd64-3.9\Release\c-blosc\internal-complibs\zlib-1.2.8
    creating build\temp.win-amd64-3.9\Release\c-blosc\internal-complibs\zstd-1.4.4
    creating build\temp.win-amd64-3.9\Release\c-blosc\internal-complibs\zstd-1.4.4\common
    creating build\temp.win-amd64-3.9\Release\c-blosc\internal-complibs\zstd-1.4.4\compress
    creating build\temp.win-amd64-3.9\Release\c-blosc\internal-complibs\zstd-1.4.4\decompress
    creating build\temp.win-amd64-3.9\Release\c-blosc\internal-complibs\zstd-1.4.4\dictBuilder
    creating build\temp.win-amd64-3.9\Release\numcodecs
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DHAVE_LZ4=1 -DHAVE_SNAPPY=1 -DHAVE_ZLIB=1 -DHAVE_ZSTD=1 -D__SSE2__=1 -D__AVX2__=1 -Ic-blosc\blosc -Ic-blosc/internal-complibs\lz4-1.9.2 -Ic-blosc/internal-complibs\snappy-1.1.1 -Ic-blosc/internal-complibs\zlib-1.2.8 -Ic-blosc/internal-complibs\zstd-1.4.4 -Ic-blosc/internal-complibs\zstd-1.4.4\common -Ic-blosc/internal-complibs\zstd-1.4.4\compress -Ic-blosc/internal-complibs\zstd-1.4.4\decompress -Ic-blosc/internal-complibs\zstd-1.4.4\deprecated -Ic-blosc/internal-complibs\zstd-1.4.4\dictBuilder -Ic-blosc/internal-complibs\zstd-1.4.4\dll -Ic-blosc/internal-complibs\zstd-1.4.4\legacy -IC:\Users\debo\AppData\Local\Programs\Python\Python39\include -IC:\Users\debo\AppData\Local\Programs\Python\Python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include /Tcc-blosc/blosc\bitshuffle-avx2.c /Fobuild\temp.win-amd64-3.9\Release\c-blosc/blosc\bitshuffle-avx2.obj -DSHUFFLE_SSE2_ENABLED -DSHUFFLE_AVX2_ENABLED
    bitshuffle-avx2.c
    C:\Users\debo\AppData\Local\Temp\pip-install-ygdv_jgu\numcodecs_ebf383ae4897413487542e3eeeb713e5\c-blosc\blosc\blosc-common.h(13): fatal error C1083: Cannot open include file: 'string.h': No such file or directory
    [numcodecs] command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    Traceback (most recent call last):
      File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\_msvccompiler.py", line 401, in compile
        self.spawn(args)
      File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\_msvccompiler.py", line 507, in spawn
        return super().spawn(cmd)
      File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\ccompiler.py", line 910, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\spawn.py", line 87, in spawn
        raise DistutilsExecError(
    distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\debo\AppData\Local\Temp\pip-install-ygdv_jgu\numcodecs_ebf383ae4897413487542e3eeeb713e5\setup.py", line 276, in build_extension
        build_ext.build_extension(self, ext)
      File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\command\build_ext.py", line 529, in build_extension
        objects = self.compiler.compile(sources,
      File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\_msvccompiler.py", line 403, in compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\debo\AppData\Local\Temp\pip-install-ygdv_jgu\numcodecs_ebf383ae4897413487542e3eeeb713e5\setup.py", line 350, in <module>     
        run_setup(with_extensions)
      File "C:\Users\debo\AppData\Local\Temp\pip-install-ygdv_jgu\numcodecs_ebf383ae4897413487542e3eeeb713e5\setup.py", line 300, in run_setup    
        setup(
      File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\command\install.py", line 546, in run
        self.run_command('build')
      File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\debo\AppData\Local\Temp\pip-install-ygdv_jgu\numcodecs_ebf383ae4897413487542e3eeeb713e5\setup.py", line 269, in run
        build_ext.run(self)
      File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\command\build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "C:\Users\debo\AppData\Local\Programs\Python\Python39\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial       
        self.build_extension(ext)
      File "C:\Users\debo\AppData\Local\Temp\pip-install-ygdv_jgu\numcodecs_ebf383ae4897413487542e3eeeb713e5\setup.py", line 279, in build_extension
        raise BuildFailed()
    __main__.BuildFailed
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\debo\AppData\Local\Programs\Python\Python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\debo\\AppData\\Local\\Temp\\pip-install-ygdv_jgu\\numcodecs_ebf383ae4897413487542e3eeeb713e5\\setup.py'"'"'; __file__='"'"'C:\\Users\\debo\\AppData\\Local\\Temp\\pip-install-ygdv_jgu\\numcodecs_ebf383ae4897413487542e3eeeb713e5\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\debo\AppData\Local\Temp\pip-record-80uvqj77\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\debo\AppData\Local\Programs\Python\Python39\Include\numcodecs' Check the logs for full command output.

```
#### Version and installation information

- [**OS**]: windows 10
- [**python**]: Python 3.9
- numcodecs latest version
- install using pip

**Comment by jakirkham** [comment]
Yeah this is expected. We haven’t added Python 3.9 support yet (not that I would expect any surprises here). Would you be willing to submit a PR? 🙂

**Comment by sparkingdark** [comment]
Actually @jakirkham I don't know how to add support can you share something of previous supporting to the library.

**Comment by dstansby** [comment]
Is this still an issue with the most recent version of numcodedcs?

**Comment by dstansby** [comment]
I'll close this since it's quite an old report - thanks for opening though, and if you have any more problems please don't hesitate to open more issues 😃
