### ISSUE TITLE
0.12.1: pep517 based build fails

### ISSUE THREAD

**Issue by kloczek** [zarr-developers/numcodecs#508]
Looks like something os wrong and ..
<details>
<summary>pep517 based build fails with</summary>

```console
+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting build dependencies for wheel...
[numcodecs] setting up Blosc extension
[numcodecs] compiling Blosc extension with SSE2 support
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
    self.run_setup()
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 305, in <module>
  File "<string>", line 287, in run_setup
  File "<string>", line 69, in blosc_extension
UnboundLocalError: local variable 'blosc_sources' referenced before assignment

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
```
</details>

**Comment by kloczek** [comment]
Gosh .. forgot that I've already opened ticket for that.
#418 duplicate.
