### ISSUE TITLE
image compressed by zarr, when reread, raise ValueError: codec not available:"imagecodecs_jpegxl"  

### ISSUE THREAD

**Issue by cynthia-you** [zarr-developers/numcodecs#547]
my codes
```
# -*- encoding:utf-8 -*-
'''
Time:     2024-06-18 16:35
Author:   fusion
IDE:      PyCharm
'''
# @Project : universal_manipulation_interface
# @File :    read_zarr.py
import zarr
import numpy as np

input_name = '/home/fusion/PycharmProjects/universal_manipulation_interface/wipe/dataset.zarr.zip'  # can read zarr.zip directly.
f = zarr.open(input_name)
a = f['data']
print(a.info)
meta=f['meta']
e_end=meta['episode_ends']
camera0_rgb=a['camera0_rgb']
print(f'camera0_rgb:{camera0_rgb.info}')
```

error:
`
/home/fusion/miniforge3/envs/umi2/bin/python3.9 /home/fusion/PycharmProjects/universal_manipulation_interface/read_zarr.py
Name        : /data
Type        : zarr.hierarchy.Group
Read-only   : False
Store type  : zarr.storage.ZipStore
No. members : 6
No. arrays  : 6
No. groups  : 0
Arrays      : camera0_rgb, robot0_demo_end_pose, robot0_demo_start_pose,
            : robot0_eef_pos, robot0_eef_rot_axis_angle, robot0_gripper_width

Traceback (most recent call last):
  File "/home/fusion/PycharmProjects/universal_manipulation_interface/read_zarr.py", line 18, in <module>
    camera0_rgb=a['camera0_rgb']
  File "/home/fusion/miniforge3/envs/umi2/lib/python3.9/site-packages/zarr/hierarchy.py", line 462, in __getitem__
    return Array(
  File "/home/fusion/miniforge3/envs/umi2/lib/python3.9/site-packages/zarr/core.py", line 224, in __init__
    self._load_metadata()
  File "/home/fusion/miniforge3/envs/umi2/lib/python3.9/site-packages/zarr/core.py", line 243, in _load_metadata
    self._load_metadata_nosync()
  File "/home/fusion/miniforge3/envs/umi2/lib/python3.9/site-packages/zarr/core.py", line 291, in _load_metadata_nosync
    self._compressor = get_codec(compressor)
  File "/home/fusion/miniforge3/envs/umi2/lib/python3.9/site-packages/numcodecs/registry.py", line 52, in get_codec
    raise ValueError('codec not available: %r' % codec_id)
ValueError: codec not available: 'imagecodecs_jpegxl'

Process finished with exit code 1
`

Looking forward your reply, thanks. ^0^

**Comment by cynthia-you** [comment]
yep ~
imagecodecs==2023.9.18
imagecodecs-lite==2022.9.26

**Comment by cynthia-you** [comment]
> try this: [cgohlke/imagecodecs#82](https://github.com/cgohlke/imagecodecs/issues/82)

it works~. Huge thanks!
